# 单个服务器配置
#spring:
#  application:
#    name: eureka-server
#server:
#  port: 10001

#eureka:
#  server:
#    enableSelfPreservation: false
#  instance:
#    hostname: localhost
  #client:
  #  registerWithEureka: false
  #  fetchRegistry: false
  #  serviceUrl:
  #    defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

# 集群配置,包括三个实例,client方在配置时,可以配置三个实例的地址。
spring:
  application:
    name: eureka-server-clustered
  profiles: peer1
server:
  port: 10001
  host: localhost
eureka:
  instance:
    hostname: eureka-peer1
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${server.host}:10002/eureka/,http://${server.host}:10003/eureka/
--- #表示文件区分
spring:
  application:
    name: eureka-server-clustered
  profiles: peer2
server:
  port: 10002
  host: localhost
eureka:
  instance:
    hostname: eureka-peer2
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${server.host}:10001/eureka/,http://${server.host}:10003/eureka/
---
spring:
  application:
    name: eureka-server-clustered
  profiles: peer3
server:
  port: 10003
  host: localhost
eureka:
  instance:
    hostname: eureka-peer3
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${server.host}:10002/eureka/,http://${server.host}:10003/eureka/